/datum/unit_test/donor_job_outfit_variants_validation/Run()
	var/datum/preference/job_outfit_variants/preference = GLOB.preference_entries[/datum/preference/job_outfit_variants]
	var/list/valid = list("Actor" = "default", "Barber" = "title_c198ec4f70")
	TEST_ASSERT(preference.is_valid(valid), "A valid associative variant map was rejected")
	TEST_ASSERT_EQUAL(json_encode(preference.deserialize(valid)), json_encode(valid), "A valid variant map changed during deserialization")
	for(var/list/input as anything in list(list("Actor", "Barber"), list(1000), list(-1), list(0)))
		TEST_ASSERT(!preference.is_valid(input), "A plain or numeric array was accepted as a variant map")
		TEST_ASSERT_EQUAL(length(preference.deserialize(input)), 0, "A plain or numeric array produced variant assignments")
	var/list/mixed = list(1000, -1, 0, "Actor" = "default", "plain array entry")
	TEST_ASSERT(!preference.is_valid(mixed), "A mixed variant list was accepted")
	var/list/sanitized = preference.deserialize(mixed)
	TEST_ASSERT_EQUAL(length(sanitized), 1, "Mixed input retained malformed entries or lost its valid entry")
	TEST_ASSERT_EQUAL(sanitized["Actor"], "default", "Mixed input lost its valid variant")
	for(var/input in list(null, 1000, "not a list"))
		TEST_ASSERT(!preference.is_valid(input), "Non-list variant data was accepted")
		TEST_ASSERT_EQUAL(length(preference.deserialize(input)), 0, "Non-list variant data produced assignments")
	var/list/at_limit = list()
	for(var/index in 1 to 128)
		at_limit["Job [index]"] = "default"
	TEST_ASSERT(preference.is_valid(at_limit), "A 128-entry map was rejected")
	TEST_ASSERT_EQUAL(length(preference.deserialize(at_limit)), 128, "The 128-entry limit was reduced")
	at_limit["Job 129"] = "default"
	TEST_ASSERT(!preference.is_valid(at_limit), "A map beyond the entry limit was accepted")
	var/list/truncated = preference.deserialize(at_limit)
	TEST_ASSERT_EQUAL(length(truncated), 128, "Deserialization exceeded its visit limit")
	TEST_ASSERT_NULL(truncated["Job 129"], "Deserialization visited the 129th entry")
	var/limit_text = repeat_string(128, "a")
	var/list/length_limit = list("[limit_text]" = limit_text)
	TEST_ASSERT(preference.is_valid(length_limit), "A 128-character key or value was rejected")
	TEST_ASSERT_EQUAL(length(preference.deserialize(length_limit)), 1, "The text length limit was reduced")
	for(var/list/input as anything in list(list("" = "default"), list("Actor" = ""), list("[limit_text]a" = "default"), list("Actor" = "[limit_text]a")))
		TEST_ASSERT(!preference.is_valid(input), "An empty or oversized key/value was accepted")
		TEST_ASSERT_EQUAL(length(preference.deserialize(input)), 0, "An empty or oversized key/value survived deserialization")
